version: '3.8'

services:
  airdrop_db:
    image: mysql
    container_name: airdrop_db
    env_file:
      - .env.sql.deploy
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql

  airdrop_app:
    image: public.ecr.aws/i0e4n2k8/appointment:beta.0
    container_name: airdrop_app
    depends_on:
      - airdrop_db
    env_file:
      - .env.deploy
    restart: always

volumes:
  mysql-data:
